package com.edgecloud.alert.service;
import java.time.Instant; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.edgecloud.alert.dto.*; import com.edgecloud.alert.entity.*; import com.edgecloud.alert.exception.MaintenanceWindowNotFoundException; import com.edgecloud.alert.exception.MaintenanceWindowValidationException; import com.edgecloud.alert.repository.*;
@Service public class MaintenanceWindowService {private final MaintenanceWindowRepository windows;private final AlertSuppressionHistoryRepository suppressions;private final MaintenanceWindowAuditRepository audit;public MaintenanceWindowService(MaintenanceWindowRepository w,AlertSuppressionHistoryRepository s,MaintenanceWindowAuditRepository a){windows=w;suppressions=s;audit=a;}
 @Transactional(readOnly=true) public List<MaintenanceWindowResponse> list(UUID project){Instant now=Instant.now();return windows.findByProjectIdOrderByStartsAtDesc(project).stream().map(w->MaintenanceWindowResponse.from(w,now,suppressions.countByMaintenanceWindowId(w.getId()))).toList();}
 @Transactional(readOnly=true) public MaintenanceWindowResponse get(UUID project,UUID id){MaintenanceWindow w=find(project,id);return MaintenanceWindowResponse.from(w,Instant.now(),suppressions.countByMaintenanceWindowId(id));}
 @Transactional public MaintenanceWindowResponse create(UUID project,MaintenanceWindowRequest r,UUID actor){validate(r);MaintenanceWindow w=windows.save(new MaintenanceWindow(project,r.scopeType(),r.serviceId(),trim(r.deviceId()),r.name(),r.reason(),r.startsAt(),r.endsAt(),r.enabled(),actor));audit.save(new MaintenanceWindowAudit(w,actor,"CREATE"));return MaintenanceWindowResponse.from(w,Instant.now(),0);}
 @Transactional public MaintenanceWindowResponse update(UUID project,UUID id,MaintenanceWindowRequest r,UUID actor){validate(r);MaintenanceWindow w=find(project,id);w.update(r.scopeType(),r.serviceId(),trim(r.deviceId()),r.name(),r.reason(),r.startsAt(),r.endsAt(),r.enabled());audit.save(new MaintenanceWindowAudit(w,actor,"UPDATE"));return MaintenanceWindowResponse.from(w,Instant.now(),suppressions.countByMaintenanceWindowId(id));}
 @Transactional public void delete(UUID project,UUID id,UUID actor){MaintenanceWindow w=find(project,id);w.disable();audit.save(new MaintenanceWindowAudit(w,actor,"DELETE"));}
 @Transactional(readOnly=true) public List<AlertSuppressionResponse> suppressions(UUID project,UUID id){find(project,id);return suppressions.findByProjectIdAndMaintenanceWindowIdOrderBySuppressedAtDesc(project,id).stream().map(AlertSuppressionResponse::from).toList();}
 private MaintenanceWindow find(UUID project,UUID id){return windows.findByIdAndProjectId(id,project).orElseThrow(()->new MaintenanceWindowNotFoundException("Maintenance window not found"));}
 private void validate(MaintenanceWindowRequest r){if(!r.endsAt().isAfter(r.startsAt()))throw new MaintenanceWindowValidationException("endsAt must be after startsAt");if(r.scopeType()==MaintenanceScopeType.PROJECT&&(r.serviceId()!=null||notBlank(r.deviceId())))throw new MaintenanceWindowValidationException("Project scope cannot specify a target");if(r.scopeType()==MaintenanceScopeType.SERVICE&&(r.serviceId()==null||notBlank(r.deviceId())))throw new MaintenanceWindowValidationException("Service scope requires only serviceId");if(r.scopeType()==MaintenanceScopeType.DEVICE&&(r.serviceId()!=null||!notBlank(r.deviceId())))throw new MaintenanceWindowValidationException("Device scope requires only deviceId");}
 private boolean notBlank(String value){return value!=null&&!value.isBlank();}private String trim(String value){return value==null?null:value.trim();}
}
