package com.edgecloud.alert.controller;
import java.util.*; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import com.edgecloud.alert.dto.*; import com.edgecloud.alert.service.*; import jakarta.validation.Valid;
@RestController @RequestMapping("/api/v2/projects/{projectId}/maintenance-windows") public class MaintenanceWindowController {private final MaintenanceWindowService service;private final AlertRuleAuthorizationService auth;public MaintenanceWindowController(MaintenanceWindowService s,AlertRuleAuthorizationService a){service=s;auth=a;}
 @GetMapping public List<MaintenanceWindowResponse> list(@PathVariable UUID projectId,Authentication a){auth.requireRead(projectId,a);return service.list(projectId);}
 @PostMapping public ResponseEntity<MaintenanceWindowResponse> create(@PathVariable UUID projectId,@Valid @RequestBody MaintenanceWindowRequest r,Authentication a){UUID actor=auth.requireMaintenanceMutation(projectId,a,r.serviceId(),r.deviceId());return ResponseEntity.status(HttpStatus.CREATED).body(service.create(projectId,r,actor));}
 @GetMapping("/{windowId}") public MaintenanceWindowResponse get(@PathVariable UUID projectId,@PathVariable UUID windowId,Authentication a){auth.requireRead(projectId,a);return service.get(projectId,windowId);}
 @PutMapping("/{windowId}") public MaintenanceWindowResponse update(@PathVariable UUID projectId,@PathVariable UUID windowId,@Valid @RequestBody MaintenanceWindowRequest r,Authentication a){UUID actor=auth.requireMaintenanceMutation(projectId,a,r.serviceId(),r.deviceId());return service.update(projectId,windowId,r,actor);}
 @DeleteMapping("/{windowId}") public ResponseEntity<Void> delete(@PathVariable UUID projectId,@PathVariable UUID windowId,Authentication a){UUID actor=auth.requireMaintenanceMutation(projectId,a,null,null);service.delete(projectId,windowId,actor);return ResponseEntity.noContent().build();}
 @GetMapping("/{windowId}/suppressions") public List<AlertSuppressionResponse> suppressions(@PathVariable UUID projectId,@PathVariable UUID windowId,Authentication a){auth.requireRead(projectId,a);return service.suppressions(projectId,windowId);}
}
