package com.edgecloud.alert.service;
import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.test.util.ReflectionTestUtils; import com.edgecloud.alert.entity.*; import com.edgecloud.alert.repository.*;
class AlertEscalationProcessorTest {
 private AlertEventRepository alerts=mock(AlertEventRepository.class); private EscalationPolicyRepository policies=mock(EscalationPolicyRepository.class); private AlertEscalationHistoryRepository history=mock(AlertEscalationHistoryRepository.class); private AlertNotificationOutboxService outbox=mock(AlertNotificationOutboxService.class); private AlertEscalationProcessor processor=new AlertEscalationProcessor(alerts,policies,history,outbox); private UUID alertId=UUID.randomUUID(),projectId=UUID.randomUUID(); private Instant opened=Instant.parse("2026-08-11T10:00:00Z");
 @Test void processesAllDueLevelsInOrderWithoutDowngrade(){AlertEvent event=event(AlertEventStatus.OPEN,Severity.MEDIUM);EscalationPolicy policy=policy();when(alerts.findByIdForEscalation(alertId)).thenReturn(Optional.of(event));when(policies.findByProjectIdAndEnabledTrue(projectId)).thenReturn(Optional.of(policy));assertThat(processor.process(alertId,opened.plusSeconds(1000))).isEqualTo(2);assertThat(event.getEscalationLevel()).isEqualTo(2);assertThat(event.getSeverity()).isEqualTo(Severity.HIGH);verify(history,times(2)).save(any());verify(outbox).enqueueEscalation(event,1,"UNACKNOWLEDGED",opened.plusSeconds(1000).plusNanos(1000));}
 @Test void acknowledgedAlertEscalatesAsUnresolved(){AlertEvent event=event(AlertEventStatus.ACKNOWLEDGED,Severity.LOW);when(alerts.findByIdForEscalation(alertId)).thenReturn(Optional.of(event));when(policies.findByProjectIdAndEnabledTrue(projectId)).thenReturn(Optional.of(policy()));when(history.existsByAlertEventIdAndLevelNumber(alertId,2)).thenReturn(true);assertThat(processor.process(alertId,opened.plusSeconds(400))).isEqualTo(1);verify(outbox).enqueueEscalation(event,1,"UNRESOLVED",opened.plusSeconds(400).plusNanos(1000));}
 @Test void skipsBeforeThresholdResolvedAndAlreadyProcessed(){AlertEvent event=event(AlertEventStatus.OPEN,Severity.LOW);when(alerts.findByIdForEscalation(alertId)).thenReturn(Optional.of(event));when(policies.findByProjectIdAndEnabledTrue(projectId)).thenReturn(Optional.of(policy()));assertThat(processor.process(alertId,opened.plusSeconds(20))).isZero();when(history.existsByAlertEventIdAndLevelNumber(alertId,1)).thenReturn(true);assertThat(processor.process(alertId,opened.plusSeconds(400))).isZero();event.setStatus(AlertEventStatus.RESOLVED);assertThat(processor.process(alertId,opened.plusSeconds(1000))).isZero();}
 private AlertEvent event(AlertEventStatus status,Severity severity){AlertEvent e=new AlertEvent();ReflectionTestUtils.setField(e,"id",alertId);e.setProjectId(projectId);e.setTriggeredAt(opened);e.setStatus(status);e.setSeverity(severity);return e;}
 private EscalationPolicy policy(){EscalationPolicy p=new EscalationPolicy(projectId,"Ops",true);ReflectionTestUtils.setField(p,"id",UUID.randomUUID());p.addLevel(new EscalationPolicyLevel(1,300,Severity.LOW,true));p.addLevel(new EscalationPolicyLevel(2,900,Severity.HIGH,true));return p;}
}
